const mongoose = require("mongoose");

const meterSchema = new mongoose.Schema(
  {
    meterId: {
      type: String,
      required: [true, "Meter ID is required"],
      unique: true,
      trim: true,
      // Format: MTR-001, MTR-002 ...
      match: [/^MTR-\d{3,}$/, "Meter ID must be in format MTR-001"],
    },

    // ─── FROM Customer Service ────────────────────────────────────
    // customerId is generated by Customer Service as CUST-001, CUST-002 ...
    // When registering a meter, Customer Service passes this customerId
    // Your meter stores it to link meter → customer
    customerId: {
      type: String,
      required: [true, "Customer ID is required"],
      trim: true,
      // Must match Customer Service format: CUST-001
      match: [/^CUST-\d{3,}$/, "Customer ID must be in format CUST-001"],
    },

    meterType: {
      type: String,
      enum: ["single-phase", "three-phase", "industrial"],
      default: "single-phase",
    },

    location: {
      address:  { type: String, required: [true, "Address is required"] },
      city:     { type: String, required: [true, "City is required"] },
      district: { type: String },
    },

    status: {
      type: String,
      enum: ["active", "inactive", "faulty", "replaced"],
      default: "active",
    },

    installedDate:      { type: Date, default: Date.now },
    lastReadingDate:    { type: Date },
    lastReadingValue:   { type: Number, default: 0 },
    totalUnitsConsumed: { type: Number, default: 0 },
  },
  { timestamps: true }
);

// Auto-generate meterId like CUST-001 does in Customer Service
meterSchema.pre("save", async function (next) {
  try {
    if (!this.meterId) {
      const count = await mongoose.model("Meter").countDocuments();
      this.meterId = `MTR-${String(count + 1).padStart(3, "0")}`;
    }
    next();
  } catch (err) {
    next(err);
  }
});

module.exports = mongoose.model("Meter", meterSchema);