const mongoose = require("mongoose");

const meterSchema = new mongoose.Schema(
  {
    meterId: {
      type: String,
      required: [true, "Meter ID is required"],
      unique: true,
      trim: true,
      match: [/^MTR-\d{3,}$/, "Meter ID must be in format MTR-001"],
    },

    // ─── FROM Customer Service ─────────────────────────────────────
    // customerId is generated by Customer Service as CUST-001
    // Customer address is already stored in Customer Service
    // so we don't require address here again
    customerId: {
      type: String,
      required: [true, "Customer ID is required"],
      trim: true,
      match: [/^CUST-\d{3,}$/, "Customer ID must be in format CUST-001"],
    },

    meterType: {
      type: String,
      enum: ["single-phase", "three-phase", "industrial"],
      default: "single-phase",
    },

    // ─── OPTIONAL ──────────────────────────────────────────────────
    // Only fill this if meter is installed at a DIFFERENT location
    // than the customer address (e.g. rental property)
    // If not given, Customer Service address is used
    location: {
      address:  { type: String, default: "" },
      city:     { type: String, default: "" },
      district: { type: String, default: "" },
    },

    status: {
      type: String,
      enum: ["active", "inactive", "faulty", "replaced"],
      default: "active",
    },

    installedDate:      { type: Date, default: Date.now },
    lastReadingDate:    { type: Date },
    lastReadingValue:   { type: Number, default: 0 },
    totalUnitsConsumed: { type: Number, default: 0 },
  },
  { timestamps: true }
);

// Auto-generate meterId like MTR-001, MTR-002 ...
meterSchema.pre("save", async function (next) {
  try {
    if (!this.meterId) {
      const count = await mongoose.model("Meter").countDocuments();
      this.meterId = `MTR-${String(count + 1).padStart(3, "0")}`;
    }
    next();
  } catch (err) {
    next(err);
  }
});

module.exports = mongoose.model("Meter", meterSchema);